# Generated by Django 3.2.5 on 2021-07-27 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEstante', models.CharField(max_length=30)),
                ('Capacidad', models.PositiveBigIntegerField()),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=30)),
                ('DescripcionProducto', models.CharField(max_length=30)),
                ('ClaveProducto', models.CharField(max_length=30)),
                ('PrecioProducto', models.CharField(max_length=10)),
                ('FechaRegistro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('Estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.estante')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProductos.producto')),
            ],
        ),
    ]
