# Generated by Django 3.2.5 on 2021-07-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ClaveProducto',
            field=models.CharField(max_length=5),
        ),
    ]
